version: '3.1'
services:
  web:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /home/yorlys/odoo/Github/odoo14-e/config:/etc/odoo
      - /home/yorlys/odoo/Github/enterprise_14:/mnt/enterprise_14
      - /home/yorlys/odoo/Github/addons-custom:/mnt/addons-custom
      - /home/yorlys/odoo/Github/OCA:/mnt/OCA
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo


    